### PR TITLE
Add command action

### PR DESCRIPTION
**Pull request by TyrenDe**
Add the command action and controls.

### CODE REVIEW

**Comment by SaviorXTanren** [comment]
1) That seems weird, we'll need to look in to that

2) I'm always fine with people breaking themselves :)

3) That's fine and fairly standard. None of the actions update themselves while they are still visible if you change things (EX: Make a Currency/Rank action and while its still visible, add a new currency).

**Comment by TyrenDe** [comment]
Okay, so 1 then:  What do you expect? Do you expect the arguments to run through the special identifier code?  Should I string.Split them to make each word a separate argument?

**Comment by SaviorXTanren** [comment]
So, here's what I would do (granted, I haven't looked at the UI code yet). I'd imagine the following:

- Large text box to enter in the arguments to run the command
- Save that large string of text just as it is in the command
- When running the action:
    - Process all of the Special Identifiers using the SpecialIdentifierStringBuilder
    - string.split the processed text and pass the split in as the arguments

**Comment by TyrenDe** [comment]
Yeah, I think I got it. Testing now, then I'll send an updated. I also did a bit of renaming/refactoring to make things more clear.

**Comment by TyrenDe** [comment]
This works better now:
Chat Text:
All: $allargs - Arg1: $arg1text - Arg2: $arg2text - Arg3: $arg3text

Just run chat command:
All: @TyrenDes - Arg1: @TyrenDes - Arg2: $arg2text - Arg3: $arg3text

Using command action
NoArgs at all
All: @TyrenDes - Arg1: @TyrenDes - Arg2: $arg2text - Arg3: $arg3text

$username
All: @TyrenDes TyrenDes - Arg1: @TyrenDes - Arg2: TyrenDes - Arg3: $arg3text

**Comment by SaviorXTanren** [comment]
Wait, I don't get the last one. If the last test is just "$username" as the arguments, wouldn't Arg2 NOT be translated to something, since there's only 1 argument?

**Pull request merged**
